openapi: 3.0.0
info:
  version: 0.0.1
  title: CrashTeam KazanExpress Analytics API
  description:
    $ref: './docs/api.md'
  termsOfService: http://marketdb.ru/terms-of-use/
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: 'https://{subdomain}.marketdb.ru/{version}'
    variables:
      subdomain:
        default: api
      version:
        enum:
          - v1
          - v2
        default: v2
security:
  - apiKey: []
paths:
#  '/product/history/{id}/{skuId}':
#    $ref: './paths/product-history@{id}{skuId}.yaml'
#  '/category/seller/{id}':
#    $ref: './paths/category-seller@{id}.yaml'
#  '/category/price/segmentation/{id}':
#    $ref: './paths/category-price-segmentation@{id}.yaml'
#  '/category/trends/{id}':
#    $ref: './paths/category-trends@{id}.yaml'
  '/product/{productId}/sku/{skuId}/sales':
    $ref: './paths/product@{productId}sku@{skuId}sales.yaml'
  '/product/sales':
    $ref: './paths/product-sales.yaml'
  '/seller/link':
    $ref: './paths/sellers.yaml'
  '/seller/{sellerLink}/overall-info':
    $ref: './paths/seller@{sellerLink}overall-info.yaml'
  '/report/seller/{sellerLink}':
    $ref: './paths/report-seller@{sellerLink}.yaml'
  '/report/category':
    $ref: './paths/report-category.yaml'
  '/report/{reportId}':
    $ref: './paths/report-download@{reportId}.yaml'
  '/report/state/{jobId}':
    $ref: './paths/report-state@{jobId}.yaml'
  '/reports':
    $ref: './paths/reports.yaml'
  '/category/{categoryId}/overall-info':
    $ref: './paths/category@{categoryId}overall-info.yaml'
components:
  securitySchemes:
    apiKey:
      $ref: './components/security-schemes/ApiKey.yaml'
